### ISSUE TITLE
tsc-watch change won't compile

### ISSUE THREAD

**Issue by Nicholaiii** [curveball/starter#11]
It looks like it ignores tsconfig; it complains about `dist/index.js` being js with no `allowJs`, when in fact it shouldn't even consider the contents of the dist folder.

**Comment by evert** [comment]
Hi! Apologies, I've missed the notification for this way back when.

It's probably too late, but is still still an issue? It seems to work for me

**Comment by Nicholaiii** [comment]
I tried cloning again recently and ran into a similar issue:

```ts
node:internal/modules/cjs/loader:936
  ^

Error: Cannot find module 'D:\Projects\untitled-status-project\dist\index.js'
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
21.06.32 - Starting compilation in watch mode...

error TS6054: File 'dist/index.js'' has an unsupported extension. The only supported extensions are '.ts', '.tsx', '.d.ts'.
  The file is in the program because:
    Root file specified for compilation

```

`npx ts-node-dev src/index.ts` works flawlessly.

**Comment by evert** [comment]
Out of curiosity, how are you running this?

**Comment by evert** [comment]
Going to close this due to no feedback

**Comment by Nicholaiii** [comment]
I apologise; I never got the notification. I just `npm run start:watch`

**Comment by evert** [comment]
@Nicholaiii running that is error free on my Ubuntu linux + node 16.13.1 + npm 8.1.2. What are you running?
